version: '3.7'
services:
  web:
    container_name: farmageo-web
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
networks:
  default:
    # Use a custom driver
    driver: farmageotest_default
