# build environment
FROM node:13.12.0-alpine as build

USER root

WORKDIR /
ENV PATH /node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm ci --silent
RUN npm install react-scripts@3.4.1 -g --silent
COPY . ./
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build ./build ./public_html
CMD ["nginx", "-g", "daemon off;"]