name: Build & Deploy
on:
  push:
    branches: [develop]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Farmageo Web
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}     
          script: |
            cd farmageo
            cd web
            git pull
            docker build -f Dockerfile.prod -t farmageoweb .
            docker tag farmageoweb:latest farmageoweb:latest
            docker-compose down
            docker-compose up -d --build